micronaut:
  server:
    port: 9087  # Changed the port to avoid conflict
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - http://localhost:9088

  security:
    enabled: true  # Micronaut security enabled to use authentication (OAuth2/Basic Auth)
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "Gj2hFC+FD2VFsuTZal3/JAvN0Fl/KSnxCDNTntEL5PQ="  # Ensure this is a secure key (for JWT, if needed)

akhq:

  connections:
    local:
      properties:
        bootstrap.servers: "localhost:9092"

  security:
    basic-auth:
      - username: admin
        password: "$2a$12$hKwQXCwRbsGKlnm.8kZoM.PdcYnXtkZCMxyV0MSvtTwdiP69ocE7C"  # BCRYPT hash of admin's password
        passwordHash: BCRYPT  # Specify BCRYPT for this user
        groups:
          - admin  # Assign the user to the admin group
      - username: reader
        password: "9e933a025f359bc7e3a3c687db60b60dc093a0b26683bd302385932adf14fd4b"  # SHA-256 hash of reader's password
        passwordHash: SHA256  # Specify SHA-256 for this user
        groups:
          - reader  # Assign the user to the reader group
