micronaut:
  server:
    port: 9087
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - http://localhost:9088
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "Gj2hFC+FD2VFsuTZal3/JAvN0Fl/KSnxCDNTntEL5PQ="  # Replace with a secure secret

akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "kafka.arpansahu.me:9093"  # Ensure this matches the actual Kafka server address and port
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="client1" password="client1-secret";
        ssl.truststore.location: "/etc/letsencrypt/live/arpansahu.me/kafka.keystore.jks"  # Path to the truststore for SSL verification
        ssl.truststore.password: "Kesar302@kafka"

  security:
    basic-auth:
      - username: admin
        password: "$2a$12$hKwQXCwRbsGKlnm.8kZoM.PdcYnXtkZCMxyV0MSvtTwdiP69ocE7C"  # BCRYPT hash
        passwordHash: BCRYPT
        groups:
          - admin
